# backend-api/Dockerfile.dev

# =========================
# Base Image
# =========================
FROM python:3.12-slim

# prevent pyc / buffer  + pip no cache
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app


# =========================
# System dependencies
# =========================
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*


# =========================
# Python dependencies (cache optimized)
# =========================
COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt


# =========================
# App source code
# =========================
COPY . .


# =========================
# Runtime
# =========================
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]